---
- name: Check SPM Monitor token
  fail:
    msg: "spm_token is mandatory"
  when: spm_token is undefined

- name: Check SPM Monitor type
  fail:
    msg: "spm_type is mandatory"
  when: spm_type is undefined

- name: Check SPM Monitor support
  fail:
    msg: "Unsupported monitor type: {{ spm_type }}"
  when: spm_type not in ['apache', 'haproxy', 'javaagent', 'memcached', 'mysql', 'nginx', 'nginx-plus', 'standalone']

- name: Configure monitor
  include: monitor-{{ spm_type }}.yml
